packages:
  - packages/*

catalogMode: prefer

catalog:
  "@angular/core": ^22.2.0
  "@types/flake-idgen": ^0.1.34
  "@types/node": ^26.1.1
  base-x: ^5.0.1
  buffer: ^6.0.3
  bumpp: ^11.1.0
  flake-idgen: ^1.4.0
  rxjs: ^7.8.2
  thrift: 0.24.0
  thrift-parser: 0.4.2
  typescript: ^7.0.2
  uuid: 14.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
