import type { Program } from "../load-schema.ts";
import type { EmittedClient } from "../emit-clients.ts";

export function emitNativeClients(program: Program): EmittedClient[] {
  const names = Object.keys(program.ast.service ?? {});
  if (!names.length) return [];
  return [
    ...names.map((name) => ({
      name: `${program.name}/${name}`,
      content: [
        "// Generated by tsthrift. Do not edit.",
        'import { createNativeClient, type NativeClientConfig } from "@vality/tsthrift/native";',
        `import { ${name}Client } from "../../models/${program.name}.js";`,
        `import { services } from "../../codecs/${program.name}.js";`,
        `export { ${name}Client };`,
        `export type ${name}ClientConfig = NativeClientConfig;`,
        `export function create${name}Client(config: ${name}ClientConfig): ${name}Client {`,
        `  return createNativeClient<${name}Client>(services[${JSON.stringify(name)}]!, config, ${JSON.stringify(name)}, ${JSON.stringify(program.name)});`,
        "}",
        "",
      ].join("\n"),
    })),
    {
      name: `${program.name}/index`,
      content: names.map((name) => `export * from "./${name}.js";`).join("\n") + "\n",
    },
  ];
}

export function emitNativeClientsIndex(programs: Program[]): string {
  return [
    "// Generated by tsthrift. Do not edit.",
    ...programs
      .filter((program) => Object.keys(program.ast.service ?? {}).length)
      .map((program) => `export * as ${program.name} from "./${program.name}/index.js";`),
    'export { SERVICES, SERVICES_LIST } from "./services.js";',
    "",
  ].join("\n");
}

export function emitNativeRegistry(programs: Program[]): string {
  const imports: string[] = [];
  const entries: string[] = [];
  for (const program of programs) {
    for (const name of Object.keys(program.ast.service ?? {})) {
      const alias = `service${entries.length}`;
      imports.push(`import * as ${alias} from "./${program.name}/${name}.js";`);
      entries.push(`[${JSON.stringify(`${program.name}.${name}`)}]: {
        serviceName: ${JSON.stringify(name)}, namespace: ${JSON.stringify(program.name)},
        token: ${alias}.${name}Client, createClient: ${alias}.create${name}Client,
        getMetadata: () => import("../metadata.json", { with: { type: "json" } }).then((m) => m.default as unknown as Metadata[])
      }`);
    }
  }
  return [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata, ThriftServiceDescriptor } from "@vality/tsthrift/native";',
    ...imports,
    `export const SERVICES = {\n${entries.join(",\n")}\n} satisfies Record<string, ThriftServiceDescriptor>;`,
    "export const SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(SERVICES);",
    "",
  ].join("\n");
}
