import type { Field, ValueType } from "@vality/tsthrift";
import type { Program } from "../load-schema.ts";
import type { I64Mode } from "../i64-mode.ts";
import { resolveReference, resolveType } from "../resolve-type.ts";
import { emitConstant } from "../emit-constant.ts";

/** Emits executable type and service contracts, with imports resolved after typedef expansion. */
export function emitCodecs(program: Program, i64: I64Mode): string {
  const imports = new Map<Program, string>();
  const reference = (owner: Program, registry: string, name: string): string => {
    if (owner === program) return `${registry}[${JSON.stringify(name)}]!`;
    if (!imports.has(owner)) imports.set(owner, `module${imports.size}`);
    return `${imports.get(owner)}.${registry}[${JSON.stringify(name)}]!`;
  };
  const codec = (owner: Program, type: ValueType): string => {
    const resolved = resolveType(owner, type);
    if (resolved.kind === "enum") return "wire.i32";
    if (resolved.kind && typeof resolved.type === "string")
      return reference(resolved.program, "types", resolved.type);
    if (typeof resolved.type === "string") {
      const scalar =
        resolved.type === "i8"
          ? "byte"
          : resolved.type === "i64" && i64 === "number"
            ? "i64Number"
            : resolved.type;
      if (scalar === "void") throw new Error("void cannot be serialized as a value");
      return `wire.${scalar}`;
    }
    const container = resolved.type;
    const item = codec(resolved.program, container.valueType);
    return container.name === "map"
      ? `wire.map(${codec(resolved.program, container.keyType)}, ${item})`
      : `wire.${container.name}(${item})`;
  };
  const fields = (definitions: Field[]): string => {
    let implicitId = -1;
    const ids = new Set<number>();
    return definitions
      .map((field) => {
        const id = field.id ?? implicitId--;
        if (field.id !== undefined && field.id < 0) implicitId = field.id - 1;
        if (ids.has(id) || id < -32768)
          throw new Error(`Conflicting or invalid field ID ${id} in ${program.path}`);
        ids.add(id);
        const attributes = [
          `id: ${id}`,
          `name: ${JSON.stringify(field.name)}`,
          `codec: ${codec(program, field.type)}`,
        ];
        if (field.option === "required") attributes.push("required: true");
        if (field.defaultValue !== undefined) {
          attributes.push(
            `defaultValue: () => (${emitConstant(program, field.type, field.defaultValue, i64, program, new Set(), "Uint8Array")})`,
          );
        }
        return `{ ${attributes.join(", ")} }`;
      })
      .join(",\n");
  };
  const structs: string[] = [];
  for (const kind of ["struct", "union", "exception"] as const) {
    for (const [name, definitions] of Object.entries(program.ast[kind] ?? {})) {
      structs.push(
        `[${JSON.stringify(name)}]: wire.struct(${JSON.stringify(name)}, () => [${fields(definitions)}], ${kind === "union"})`,
      );
    }
  }
  const services: string[] = [];
  const emitted = new Set<string>();
  const emitService = (name: string) => {
    if (emitted.has(name)) return;
    const service = program.ast.service![name]!;
    let parent = "";
    if (service.extends) {
      const resolved = resolveReference(program, service.extends);
      if (resolved.program === program) emitService(resolved.name);
      parent = `...${reference(resolved.program, "services", resolved.name)},`;
    }
    const methods = Object.values(service.functions).map((method) => {
      if (method.oneway && (method.type !== "void" || method.throws.length))
        throw new Error(`Oneway method must return void without throws: ${name}.${method.name}`);
      if (method.throws.some((field) => field.id === 0 || field.name === "success"))
        throw new Error(`Exception collides with result field: ${name}.${method.name}`);
      const result: Field[] =
        method.type === "void" ? [] : [{ id: 0, name: "success", type: method.type }];
      result.push(
        ...method.throws.map((field) => ({
          ...field,
          option: "optional" as const,
          defaultValue: undefined,
        })),
      );
      return `[${JSON.stringify(method.name)}]: {
        args: wire.struct(${JSON.stringify(`${name}.${method.name}.args`)}, () => [${fields(method.args)}]),
        argumentNames: ${JSON.stringify(method.args.map((field) => field.name))},
        result: wire.struct(${JSON.stringify(`${name}.${method.name}.result`)}, () => [${fields(result)}]),
        exceptions: ${JSON.stringify(method.throws.map((field) => field.name))},
        returns: ${method.type !== "void"}, oneway: ${method.oneway}
      }`;
    });
    services.push(`services[${JSON.stringify(name)}] = { ${parent}\n${methods.join(",\n")} };`);
    emitted.add(name);
  };
  for (const name of Object.keys(program.ast.service ?? {})) emitService(name);
  return [
    "// Generated by tsthrift. Do not edit.",
    'import * as wire from "@vality/tsthrift/native";',
    ...Array.from(
      imports,
      ([owner, alias]) => `import * as ${alias} from ${JSON.stringify(`./${owner.name}.js`)};`,
    ),
    `export const types: Record<string, wire.Codec> = {\n${structs.join(",\n")}\n};`,
    "export const services: Record<string, Record<string, wire.MethodCodec>> = Object.create(null);",
    ...services,
    "",
  ].join("\n");
}
