import type { Field, ValueType } from "../metadata/schema.ts";
import type { Program } from "./load-schema.ts";
import { emitConstant } from "./emit-constant.ts";
import { enumMembers } from "./enum-members.ts";
import type { I64Mode } from "./i64-mode.ts";

function tsType(type: ValueType, i64: I64Mode): string {
  if (typeof type !== "string") {
    if (type.name === "map")
      return `globalThis.Map<${tsType(type.keyType, i64)}, ${tsType(type.valueType, i64)}>`;
    return type.name === "set"
      ? `globalThis.Set<${tsType(type.valueType, i64)}>`
      : `${tsType(type.valueType, i64)}[]`;
  }
  if (type === "i64") return i64;
  if (["byte", "i8", "i16", "i32", "double"].includes(type)) return "number";
  if (type === "bool") return "boolean";
  if (type === "binary") return "string";
  return type;
}

function fieldsBody(fields: Field[], union: boolean, i64: I64Mode): string {
  return fields
    .map(
      (field) =>
        `  ${JSON.stringify(field.name)}${union || field.option === "optional" ? "?" : ""}: ${tsType(field.type, i64)};`,
    )
    .join("\n");
}

/** Emits public models only; executable RPC clients remain internal JS artifacts. */
export function emitModels(program: Program, i64: I64Mode = "number"): string {
  const lines = ["// Generated by tsthrift. Do not edit."];
  for (const [alias, included] of program.includes) {
    lines.push(`import * as ${alias} from ${JSON.stringify(`./${included.name}.js`)};`);
    lines.push(`export { ${alias} };`);
  }
  for (const [name, alias] of Object.entries(program.ast.typedef ?? {})) {
    lines.push(`export type ${name} = ${tsType(alias.type, i64)};`);
  }
  for (const [name, enumeration] of Object.entries(program.ast.enum ?? {})) {
    const members = enumMembers(enumeration, `${program.path}:${name}`).map(
      (item) => `  ${JSON.stringify(item.name)} = ${item.value},`,
    );
    lines.push(`export enum ${name} {\n${members.join("\n")}\n}`);
  }
  for (const kind of ["struct", "union", "exception"] as const) {
    for (const [name, fields] of Object.entries(program.ast[kind] ?? {})) {
      lines.push(`export interface ${name} {\n${fieldsBody(fields, kind === "union", i64)}\n}`);
    }
  }
  for (const [name, constant] of Object.entries(program.ast.const ?? {})) {
    lines.push(
      `export const ${name}: ${tsType(constant.type, i64)} = ${emitConstant(program, constant.type, constant.value, i64)};`,
    );
  }
  for (const [name, service] of Object.entries(program.ast.service ?? {})) {
    const parent = service.extends ? ` extends ${service.extends}Client` : "";
    const methods = Object.values(service.functions).map((method) => {
      const parameters = method.args
        .map((field) => `${field.name}: ${tsType(field.type, i64)}`)
        .join(", ");
      return `  ${JSON.stringify(method.name)}(${parameters}): Promise<${tsType(method.type, i64)}>;`;
    });
    lines.push(`export interface ${name}Client${parent} {\n${methods.join("\n")}\n}`);
  }
  return `${lines.join("\n\n")}\n`;
}
