import type { Field } from "@vality/tsthrift";
import type { Program } from "./load-schema.ts";
import { emitConstant } from "./emit-constant.ts";
import { enumMembers } from "./enum-members.ts";
import type { I64Mode } from "./i64-mode.ts";
import { tsType } from "./ts-type.ts";

function fieldsBody(fields: Field[], union: boolean, i64: I64Mode): string {
  return fields
    .map(
      (field) =>
        `  ${JSON.stringify(field.name)}${union || field.option !== "required" ? "?" : ""}: ${tsType(field.type, i64)};`,
    )
    .join("\n");
}

/** Emits public value models and service tokens; client implementations are emitted separately. */
export function emitModels(program: Program, i64: I64Mode = "bigint"): string {
  const lines = ["// Generated by tsthrift. Do not edit."];
  for (const [alias, included] of program.includes) {
    const specifier = included.external
      ? included.external.importPath
      : `../${included.name}/models.js`;
    lines.push(`import * as ${alias} from ${JSON.stringify(specifier)};`);
    lines.push(`export { ${alias} };`);
  }

  for (const [name, alias] of Object.entries(program.ast.typedef ?? {})) {
    lines.push(`export type ${name} = ${tsType(alias.type, i64)};`);
  }
  for (const [name, enumeration] of Object.entries(program.ast.enum ?? {})) {
    const members = enumMembers(enumeration, `${program.path}:${name}`).map(
      (item) => `  ${JSON.stringify(item.name)} = ${item.value},`,
    );
    lines.push(`export enum ${name} {\n${members.join("\n")}\n}`);
  }
  for (const kind of ["struct", "union", "exception"] as const) {
    for (const [name, fields] of Object.entries(program.ast[kind] ?? {})) {
      lines.push(`export interface ${name} {\n${fieldsBody(fields, kind === "union", i64)}\n}`);
    }
  }
  for (const [name, constant] of Object.entries(program.ast.const ?? {})) {
    lines.push(
      `export const ${name}: ${tsType(constant.type, i64)} = ${emitConstant(program, constant.type, constant.value, i64, program, new Set())};`,
    );
  }
  return `${lines.join("\n\n")}\n`;
}
