import type { Schema } from "./load-schema.ts";

/** Emits root exports without exposing the main namespace's local metadata loader. */
export function emitRootIndex(
  schema: Schema,
  main: string | undefined,
  hasServices: boolean,
): string {
  const rootIndexLines = [
    "// Generated by tsthrift. Do not edit.",
    'export { TSTHRIFT_BUILD } from "./build.js";',
  ];
  const mainProgramName =
    main ?? (schema.localPrograms.length === 1 ? schema.localPrograms[0]?.name : undefined);

  if (mainProgramName) {
    const mainProgram = schema.localPrograms.find((p) => p.name === mainProgramName);
    if (!mainProgram) {
      throw new Error(
        `Main module "${mainProgramName}" not found in schema. Available: ${schema.localPrograms.map((p) => p.name).join(", ")}`,
      );
    }
    rootIndexLines.push(
      `export * from "./${mainProgram.name}/models.js";`,
      `export { thriftMetadata } from "./${mainProgram.name}/metadata.js";`,
    );
    if (hasServices && Object.keys(mainProgram.ast.service ?? {}).length > 0) {
      rootIndexLines.push(`export * from "./${mainProgram.name}/services/index.js";`);
    }
  }

  if (hasServices) {
    rootIndexLines.push('export { THRIFT_SERVICES, THRIFT_SERVICES_LIST } from "./services.js";');
  }
  rootIndexLines.push(
    'export { THRIFT_NAMESPACES, loadThriftMetadataByNamespaces } from "./metadata.js";',
  );
  if (schema.externalPrograms.length > 0) {
    rootIndexLines.push(
      'export { EXTERNAL_NAMESPACES } from "./metadata.js";',
      'export type { ExternalNamespaceDescriptor } from "./metadata.js";',
    );
  }
  return `${rootIndexLines.join("\n")}\n`;
}
