import type { Program } from "./load-schema.ts";

export interface EmittedClient {
  name: string;
  content: string;
}

/**
 * Emits typed client factories for services defined in a Thrift program.
 */
export function emitClients(program: Program): EmittedClient[] {
  const clients: EmittedClient[] = [];
  const services = program.ast.service ?? {};

  for (const [serviceName] of Object.entries(services)) {
    const lines = [
      "// Generated by tsthrift. Do not edit.",
      'import { createThriftClient, type ThriftClientConfig } from "@vality/tsthrift";',
      `import type { ${serviceName}Client } from "../models/${program.name}.js";`,
      `import * as InternalModule from "../internal/${serviceName}.js";`,
      "",
      `export type { ${serviceName}Client };`,
      "",
      `export interface ${serviceName}ClientConfig extends Omit<ThriftClientConfig, "serviceName"> {}`,
      "",
      "const InternalClient =",
      "  (InternalModule as any).Client ?? (InternalModule as any).default?.Client ?? InternalModule;",
      "",
      `export function create${serviceName}Client(config: ${serviceName}ClientConfig): ${serviceName}Client {`,
      `  return createThriftClient<${serviceName}Client>(InternalClient, {`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      '    metadata: () => import("../metadata.json"),',
      "    ...config,",
      "  });",
      "}",
      "",
    ];

    clients.push({
      name: serviceName,
      content: lines.join("\n"),
    });
  }

  return clients;
}

/**
 * Emits the index re-exporting all generated client factories.
 */
export function emitClientsIndex(clients: EmittedClient[]): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...clients.map((client) => `export * from "./${client.name}.js";`),
    "",
  ];
  return lines.join("\n");
}
