import type { Program } from "./load-schema.ts";

export interface EmittedClient {
  name: string;
  content: string;
}

/**
 * Emits typed client factories for services defined in a Thrift program.
 */
export function emitClients(program: Program): EmittedClient[] {
  const clients: EmittedClient[] = [];
  const services = program.ast.service ?? {};

  for (const [serviceName] of Object.entries(services)) {
    const lines = [
      "// Generated by tsthrift. Do not edit.",
      'import { createThriftClient, type ThriftClientConfig } from "@vality/tsthrift";',
      `import { ${serviceName}Client } from "../models/${program.name}.js";`,
      `import * as InternalModule from "../internal/${serviceName}.js";`,
      "",
      `export { ${serviceName}Client };`,
      "",
      `export interface ${serviceName}ClientConfig extends Omit<ThriftClientConfig, "serviceName"> {}`,
      "",
      "const InternalClient =",
      "  (InternalModule as any).Client ?? (InternalModule as any).default?.Client ?? InternalModule;",
      "",
      `export function create${serviceName}Client(config: ${serviceName}ClientConfig): ${serviceName}Client {`,
      `  return createThriftClient<${serviceName}Client>(InternalClient, {`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      '    metadata: () => import("../metadata.json", { with: { type: "json" } }),',
      "    ...config,",
      "  });",
      "}",
      "",
    ];

    clients.push({
      name: serviceName,
      content: lines.join("\n"),
    });
  }

  return clients;
}

export interface ClientServiceEntry {
  serviceName: string;
  programName: string;
}

/**
 * Emits the services registry (SERVICES and SERVICES_LIST) containing descriptors for all services.
 */
export function emitServicesRegistry(services: ClientServiceEntry[]): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata, ThriftServiceDescriptor } from "@vality/tsthrift";',
  ];

  for (const s of services) {
    lines.push(
      `import { ${s.serviceName}Client, create${s.serviceName}Client } from "./${s.serviceName}.js";`,
    );
  }

  lines.push("");
  lines.push("export interface ServicesRegistry {");
  for (const s of services) {
    lines.push(`  ${s.serviceName}: ThriftServiceDescriptor<${s.serviceName}Client>;`);
  }
  lines.push("}");
  lines.push("");
  lines.push("export const SERVICES: ServicesRegistry = {");
  for (const s of services) {
    lines.push(`  ${s.serviceName}: {`);
    lines.push(`    serviceName: ${JSON.stringify(s.serviceName)},`);
    lines.push(`    namespace: ${JSON.stringify(s.programName)},`);
    lines.push(`    token: ${s.serviceName}Client,`);
    lines.push(`    createClient: create${s.serviceName}Client,`);
    lines.push(
      '    getMetadata: () => import("../metadata.json", { with: { type: "json" } }).then((m) => m.default as unknown as Metadata[]),',
    );
    lines.push("  },");
  }
  lines.push("};");
  lines.push("");
  lines.push("export const SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(SERVICES);");
  lines.push("");

  return lines.join("\n");
}

/**
 * Emits the index re-exporting all generated client factories and services registry.
 */
export function emitClientsIndex(clients: EmittedClient[]): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...clients.map((client) => `export * from "./${client.name}.js";`),
    'export * from "./services.js";',
    "",
  ];
  return lines.join("\n");
}
