import type { ValueType } from "@vality/tsthrift";
import type { Program, Schema } from "./load-schema.ts";
import type { I64Mode } from "./i64-mode.ts";
import type { BinaryTargetType } from "./emit-models.ts";

export interface EmittedServiceFile {
  programName: string;
  serviceName: string;
  relativePath: string;
  content: string;
}

function serviceTsType(type: ValueType, i64: I64Mode, binary: BinaryTargetType): string {
  if (typeof type !== "string") {
    if (type.name === "map")
      return `globalThis.Map<${serviceTsType(type.keyType, i64, binary)}, ${serviceTsType(type.valueType, i64, binary)}>`;
    return type.name === "set"
      ? `globalThis.Set<${serviceTsType(type.valueType, i64, binary)}>`
      : `${serviceTsType(type.valueType, i64, binary)}[]`;
  }
  if (type === "void") return "void";
  if (type === "string") return "string";
  if (type === "bool") return "boolean";
  if (type === "i64") return i64;
  if (["byte", "i8", "i16", "i32", "double"].includes(type)) return "number";
  if (type === "binary") return binary;
  if (type === "uuid") return "string";
  return `models.${type}`;
}

export function emitProgramServices(
  program: Program,
  i64: I64Mode = "bigint",
  binary: BinaryTargetType = "Uint8Array",
): EmittedServiceFile[] {
  const files: EmittedServiceFile[] = [];
  const services = program.ast.service ?? {};

  for (const [serviceName, service] of Object.entries(services)) {
    let parent = "";
    let parentImport = "";
    if (service.extends) {
      if (service.extends.includes(".")) {
        const [incNamespace, incService] = service.extends.split(".");
        parentImport = `import type { ${incService} as ${incNamespace}_${incService} } from "../../${program.includes.get(incNamespace)!.name}/services/${incService}.js";\n`;
        parent = ` extends ${incNamespace}_${incService}`;
      } else {
        parentImport = `import type { ${service.extends} } from "./${service.extends}.js";\n`;
        parent = ` extends ${service.extends}`;
      }
    }

    const methods = Object.values(service.functions).map((method) => {
      const names = new Set(method.args.map((field) => field.name));
      let optionsName = "options";
      while (names.has(optionsName)) optionsName = `_${optionsName}`;
      const parameters = [
        ...method.args.map((field) => `${field.name}: ${serviceTsType(field.type, i64, binary)}`),
        `${optionsName}?: models.RequestOptions`,
      ].join(", ");
      return `  ${JSON.stringify(method.name)}(${parameters}): Promise<${serviceTsType(method.type, i64, binary)}>;`;
    });

    const lines = [
      "// Generated by tsthrift. Do not edit.",
      'import { createLazyMetadataClient, type MetadataClientConfig, type ThriftServiceDescriptor } from "@vality/tsthrift";',
      'import { loadMetadata } from "../../metadata.js";',
      'import type * as models from "../models.js";',
    ];

    if (parentImport) {
      lines.push(parentImport.trim());
    }

    lines.push(
      "",
      `export interface ${serviceName}${parent} {`,
      methods.join("\n"),
      "}",
      "",
      `export interface ${serviceName}Config extends Omit<MetadataClientConfig, "serviceName" | "namespace" | "metadata" | "i64Mode"> {`,
      '  metadata?: MetadataClientConfig["metadata"];',
      "}",
      "",
      `const defaultMetadata = () => loadMetadata(${JSON.stringify(program.name)});`,
      "",
      `/**`,
      ` * Creates a service client for ${serviceName} that lazily initializes metadata and codecs.`,
      ` */`,
      `export function create${serviceName}(config: ${serviceName}Config): ${serviceName} {`,
      `  return createLazyMetadataClient<${serviceName}>({`,
      `    ...config,`,
      `    i64Mode: ${JSON.stringify(i64)},`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      `    metadata: config.metadata ?? defaultMetadata,`,
      `  });`,
      `}`,
      "",
      `/**`,
      ` * Thrift service descriptor for ${serviceName}.`,
      ` */`,
      `export const ${serviceName}: ThriftServiceDescriptor<${serviceName}> = {`,
      `  serviceName: ${JSON.stringify(serviceName)},`,
      `  namespace: ${JSON.stringify(program.name)},`,
      `  createService: create${serviceName},`,
      `  getMetadata: defaultMetadata,`,
      `};`,
      "",
      `/**`,
      ` * Alias for ${serviceName} descriptor.`,
      ` */`,
      `export const ${serviceName}Descriptor: ThriftServiceDescriptor<${serviceName}> = ${serviceName};`,
      "",
    );

    files.push({
      programName: program.name,
      serviceName,
      relativePath: `${serviceName}.ts`,
      content: lines.join("\n"),
    });
  }

  return files;
}

export function emitProgramIndex(program: Program): string {
  const services = Object.keys(program.ast.service ?? {});
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...services.map((name) => `export * from "./${name}.js";`),
    "",
  ];
  return lines.join("\n");
}

export function emitServicesRegistry(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { ThriftServiceDescriptor } from "@vality/tsthrift";',
  ];

  const serviceList: { programName: string; serviceName: string }[] = [];
  for (const program of schema.programs) {
    for (const serviceName of Object.keys(program.ast.service ?? {})) {
      serviceList.push({ programName: program.name, serviceName });
    }
  }

  for (const s of serviceList) {
    lines.push(
      `import { type ${s.serviceName} as ${s.programName}_${s.serviceName}, ${s.serviceName} as ${s.programName}_${s.serviceName}Descriptor } from "./${s.programName}/services/${s.serviceName}.js";`,
    );
  }

  lines.push("");
  lines.push("export interface ServicesRegistry {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ThriftServiceDescriptor<${s.programName}_${s.serviceName}>;`,
    );
  }
  lines.push("}");
  lines.push("");
  lines.push("export const SERVICES: ServicesRegistry = {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ${s.programName}_${s.serviceName}Descriptor,`,
    );
  }

  lines.push("};");
  lines.push("");
  lines.push("export const SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(SERVICES);");
  lines.push("");

  return lines.join("\n");
}
