import type { Field, ValueType } from "@vality/tsthrift";
import type { Program } from "./load-schema.ts";
import { emitConstant } from "./emit-constant.ts";
import { enumMembers } from "./enum-members.ts";
import type { I64Mode } from "./i64-mode.ts";

export type BinaryTargetType = "string" | "Uint8Array";

function tsType(type: ValueType, i64: I64Mode, binary: BinaryTargetType): string {
  if (typeof type !== "string") {
    if (type.name === "map")
      return `globalThis.Map<${tsType(type.keyType, i64, binary)}, ${tsType(type.valueType, i64, binary)}>`;
    return type.name === "set"
      ? `globalThis.Set<${tsType(type.valueType, i64, binary)}>`
      : `${tsType(type.valueType, i64, binary)}[]`;
  }
  if (type === "i64") return i64;
  if (["byte", "i8", "i16", "i32", "double"].includes(type)) return "number";
  if (type === "bool") return "boolean";
  if (type === "binary") return binary;
  if (type === "uuid") return "string";
  return type;
}

function fieldsBody(
  fields: Field[],
  union: boolean,
  i64: I64Mode,
  binary: BinaryTargetType,
): string {
  return fields
    .map(
      (field) =>
        `  ${JSON.stringify(field.name)}${union || field.option === "optional" ? "?" : ""}: ${tsType(field.type, i64, binary)};`,
    )
    .join("\n");
}

/** Emits public value models and service tokens; client implementations are emitted separately. */
export function emitModels(
  program: Program,
  i64: I64Mode = "bigint",
  binary: BinaryTargetType = "Uint8Array",
): string {
  const lines = ["// Generated by tsthrift. Do not edit."];
  for (const [alias, included] of program.includes) {
    lines.push(`import * as ${alias} from ${JSON.stringify(`../${included.name}/models.js`)};`);
    lines.push(`export { ${alias} };`);
  }

  for (const [name, alias] of Object.entries(program.ast.typedef ?? {})) {
    lines.push(`export type ${name} = ${tsType(alias.type, i64, binary)};`);
  }
  for (const [name, enumeration] of Object.entries(program.ast.enum ?? {})) {
    const members = enumMembers(enumeration, `${program.path}:${name}`).map(
      (item) => `  ${JSON.stringify(item.name)} = ${item.value},`,
    );
    lines.push(`export enum ${name} {\n${members.join("\n")}\n}`);
  }
  for (const kind of ["struct", "union", "exception"] as const) {
    for (const [name, fields] of Object.entries(program.ast[kind] ?? {})) {
      lines.push(
        `export interface ${name} {\n${fieldsBody(fields, kind === "union", i64, binary)}\n}`,
      );
    }
  }
  for (const [name, constant] of Object.entries(program.ast.const ?? {})) {
    lines.push(
      `export const ${name}: ${tsType(constant.type, i64, binary)} = ${emitConstant(program, constant.type, constant.value, i64, program, new Set(), binary)};`,
    );
  }
  return `${lines.join("\n\n")}\n`;
}
