import type { Program, Schema } from "./load-schema.ts";

export interface EmittedClientFile {
  programName: string;
  serviceName: string;
  relativePath: string;
  content: string;
}

export function emitProgramClients(program: Program): EmittedClientFile[] {
  const files: EmittedClientFile[] = [];
  const services = program.ast.service ?? {};

  for (const [serviceName] of Object.entries(services)) {
    const lines = [
      "// Generated by tsthrift. Do not edit.",
      'import { createLazyMetadataClient, createMetadataClient, type MetadataClientConfig } from "@vality/tsthrift";',
      `import type { ${serviceName}Client } from "../../models/${program.name}.js";`,
      "",
      `export type { ${serviceName}Client };`,
      "",
      `export interface ${serviceName}ClientConfig extends Omit<MetadataClientConfig, "serviceName" | "namespace" | "metadata"> {`,
      '  metadata?: MetadataClientConfig["metadata"];',
      "}",
      "",
      'const defaultMetadata = () => import("../../metadata.json", { with: { type: "json" } }) as unknown as Promise<{ default: any }>;',
      "",
      `/**`,
      ` * Creates a synchronous proxy client for ${serviceName} that lazily initializes metadata and codecs.`,
      ` */`,
      `export function create${serviceName}Client(config: ${serviceName}ClientConfig): ${serviceName}Client {`,
      `  return createLazyMetadataClient<${serviceName}Client>({`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      `    metadata: config.metadata ?? defaultMetadata,`,
      `    ...config,`,
      `  });`,
      `}`,
      "",
      `/**`,
      ` * Asynchronously creates an initialized client for ${serviceName}.`,
      ` */`,
      `export async function createAsync${serviceName}Client(config: ${serviceName}ClientConfig): Promise<${serviceName}Client> {`,
      `  return createMetadataClient<${serviceName}Client>({`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      `    metadata: config.metadata ?? defaultMetadata,`,
      `    ...config,`,
      `  });`,
      `}`,
      "",
    ];

    files.push({
      programName: program.name,
      serviceName,
      relativePath: `${program.name}/${serviceName}.ts`,
      content: lines.join("\n"),
    });
  }

  return files;
}

export function emitProgramIndex(program: Program): string {
  const services = Object.keys(program.ast.service ?? {});
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...services.map((name) => `export * from "./${name}.js";`),
    "",
  ];
  return lines.join("\n");
}

export function emitServicesRegistry(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { ThriftServiceDescriptor } from "@vality/tsthrift";',
  ];

  const serviceList: { programName: string; serviceName: string }[] = [];
  for (const program of schema.programs) {
    for (const serviceName of Object.keys(program.ast.service ?? {})) {
      serviceList.push({ programName: program.name, serviceName });
    }
  }

  for (const s of serviceList) {
    lines.push(
      `import { type ${s.serviceName}Client as ${s.programName}_${s.serviceName}Client, create${s.serviceName}Client as ${s.programName}_create${s.serviceName}Client } from "./${s.programName}/${s.serviceName}.js";`,
    );
  }

  lines.push("");
  lines.push("export interface ServicesRegistry {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ThriftServiceDescriptor<${s.programName}_${s.serviceName}Client>;`,
    );
  }
  lines.push("}");
  lines.push("");
  lines.push("export const SERVICES: ServicesRegistry = {");
  for (const s of serviceList) {
    lines.push(`  "${s.programName}.${s.serviceName}": {`);
    lines.push(`    serviceName: ${JSON.stringify(s.serviceName)},`);
    lines.push(`    namespace: ${JSON.stringify(s.programName)},`);
    lines.push(`    createClient: ${s.programName}_create${s.serviceName}Client,`);
    lines.push(
      '    getMetadata: () => import("../metadata.json", { with: { type: "json" } }).then((m) => (m.default ?? m) as any),',
    );
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");
  lines.push("export const SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(SERVICES);");
  lines.push("");

  return lines.join("\n");
}

export function emitClientsRootIndex(schema: Schema): string {
  const lines = ["// Generated by tsthrift. Do not edit."];
  for (const program of schema.programs) {
    if (program.ast.service && Object.keys(program.ast.service).length > 0) {
      lines.push(`export * as ${program.name} from "./${program.name}/index.js";`);
    }
  }
  lines.push('export * from "./services.js";');
  lines.push("");
  return lines.join("\n");
}
