import type { Program, Schema } from "./load-schema.ts";

export interface EmittedServiceFile {
  programName: string;
  serviceName: string;
  relativePath: string;
  content: string;
}

export function emitProgramServices(program: Program): EmittedServiceFile[] {
  const files: EmittedServiceFile[] = [];
  const services = program.ast.service ?? {};

  for (const [serviceName] of Object.entries(services)) {
    const lines = [
      "// Generated by tsthrift. Do not edit.",
      'import { createLazyMetadataClient, type MetadataClientConfig, type ThriftServiceDescriptor } from "@vality/tsthrift";',
      'import { loadMetadata } from "../../metadata/index.js";',
      `import type { ${serviceName} } from "../../models/${program.name}.js";`,
      "",
      `export type { ${serviceName} };`,
      "",
      `export interface ${serviceName}Config extends Omit<MetadataClientConfig, "serviceName" | "namespace" | "metadata"> {`,
      '  metadata?: MetadataClientConfig["metadata"];',
      "}",
      "",
      `const defaultMetadata = () => loadMetadata(${JSON.stringify(program.name)});`,
      "",
      `/**`,
      ` * Creates a service client for ${serviceName} that lazily initializes metadata and codecs.`,
      ` */`,
      `export function create${serviceName}(config: ${serviceName}Config): ${serviceName} {`,
      `  return createLazyMetadataClient<${serviceName}>({`,
      `    serviceName: ${JSON.stringify(serviceName)},`,
      `    namespace: ${JSON.stringify(program.name)},`,
      `    metadata: config.metadata ?? defaultMetadata,`,
      `    ...config,`,
      `  });`,
      `}`,
      "",
      `/**`,
      ` * Thrift service descriptor for ${serviceName}.`,
      ` */`,
      `export const ${serviceName}Descriptor: ThriftServiceDescriptor<${serviceName}> = {`,
      `  serviceName: ${JSON.stringify(serviceName)},`,
      `  namespace: ${JSON.stringify(program.name)},`,
      `  createService: create${serviceName},`,
      `  getMetadata: defaultMetadata,`,
      `};`,
      "",
    ];

    files.push({
      programName: program.name,
      serviceName,
      relativePath: `${program.name}/${serviceName}.ts`,
      content: lines.join("\n"),
    });
  }

  return files;
}

export function emitProgramIndex(program: Program): string {
  const services = Object.keys(program.ast.service ?? {});
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...services.map((name) => `export * from "./${name}.js";`),
    "",
  ];
  return lines.join("\n");
}

export function emitServicesRegistry(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { ThriftServiceDescriptor } from "@vality/tsthrift";',
  ];

  const serviceList: { programName: string; serviceName: string }[] = [];
  for (const program of schema.programs) {
    for (const serviceName of Object.keys(program.ast.service ?? {})) {
      serviceList.push({ programName: program.name, serviceName });
    }
  }

  for (const s of serviceList) {
    lines.push(
      `import { type ${s.serviceName} as ${s.programName}_${s.serviceName}, ${s.serviceName}Descriptor as ${s.programName}_${s.serviceName}Descriptor } from "./${s.programName}/${s.serviceName}.js";`,
    );
  }

  lines.push("");
  lines.push("export interface ServicesRegistry {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ThriftServiceDescriptor<${s.programName}_${s.serviceName}>;`,
    );
  }
  lines.push("}");
  lines.push("");
  lines.push("export const SERVICES: ServicesRegistry = {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ${s.programName}_${s.serviceName}Descriptor,`,
    );
  }

  lines.push("};");
  lines.push("");
  lines.push("export const SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(SERVICES);");
  lines.push("");

  return lines.join("\n");
}

export function emitServicesRootIndex(schema: Schema): string {
  const lines = ["// Generated by tsthrift. Do not edit."];
  for (const program of schema.programs) {
    if (program.ast.service && Object.keys(program.ast.service).length > 0) {
      lines.push(`export * as ${program.name} from "./${program.name}/index.js";`);
    }
  }
  lines.push('export * from "./services.js";');
  lines.push("");
  return lines.join("\n");
}
