import type { Program, Schema } from "./schema.ts";

export function emitProgramIndex(program: Program): string {
  const services = Object.keys(program.ast.service ?? {});
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    ...services.map((name) => `export * from "./${name}.js";`),
    "",
  ];
  return lines.join("\n");
}

export function emitServicesRegistry(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { ThriftServiceDescriptor } from "@vality/tsthrift";',
  ];

  const serviceList: { programName: string; serviceName: string }[] = [];
  for (const program of schema.localPrograms) {
    for (const serviceName of Object.keys(program.ast.service ?? {})) {
      serviceList.push({ programName: program.name, serviceName });
    }
  }

  for (const s of serviceList) {
    lines.push(
      `import { type ${s.serviceName} as ${s.programName}_${s.serviceName}, type ${s.serviceName}Errors as ${s.programName}_${s.serviceName}Errors, ${s.serviceName} as ${s.programName}_${s.serviceName}Descriptor } from "./${s.programName}/services/${s.serviceName}.js";`,
    );
  }

  lines.push("");
  lines.push("export interface ServicesRegistry {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ThriftServiceDescriptor<${s.programName}_${s.serviceName}, ${s.programName}_${s.serviceName}Errors>;`,
    );
  }
  lines.push("}");
  lines.push("export const THRIFT_SERVICES: ServicesRegistry = {");
  for (const s of serviceList) {
    lines.push(
      `  "${s.programName}.${s.serviceName}": ${s.programName}_${s.serviceName}Descriptor,`,
    );
  }

  lines.push("};");
  lines.push("");
  lines.push(
    "export const THRIFT_SERVICES_LIST: ThriftServiceDescriptor[] = Object.values(THRIFT_SERVICES);",
  );
  lines.push("");

  return lines.join("\n");
}
