import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSchema } from "./load-schema.ts";
import { validateSchema } from "./validate-schema.ts";
import { emitModels } from "./emit-models.ts";
import {
  emitProgramClients,
  emitProgramIndex,
  emitServicesRegistry,
  emitClientsRootIndex,
} from "./emit-clients.ts";
import { publishOutput } from "./publish-output.ts";
import { emitMetadata } from "../metadata/emit-metadata.ts";
import { emitSplitMetadata, emitMetadataLoader } from "../metadata/emit-split-metadata.ts";
import { parseI64Mode } from "./i64-mode.ts";
import type { I64Mode } from "./i64-mode.ts";

export interface GenerateOptions {
  input: string;
  output: string;
  includes?: string[];
  namespaces?: string[];
  models?: boolean;
  clients?: boolean;
  minify?: boolean;
  splitMetadata?: boolean;
  metadataJson?: boolean;
  package?: boolean;
  packageName?: string;
  i64?: I64Mode;
}

export interface GenerateResult {
  i64: I64Mode;
  models: boolean;
  clients: boolean;
  compilerVersion?: string;
  modules: string[];
  output: string;
}

export async function generate(options: GenerateOptions): Promise<GenerateResult> {
  const input = path.resolve(options.input);
  const output = path.resolve(options.output);
  const includes = [input, ...(options.includes ?? []).map((root) => path.resolve(root))];
  const shouldEmitModels = options.models ?? true;
  const shouldEmitClients = shouldEmitModels && options.clients !== false;
  const i64 = parseI64Mode(options.i64);

  const schema = await loadSchema(input, includes, options.namespaces);
  for (const program of schema.programs) {
    const relative = path.relative(output, program.filename);
    if (!relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)) {
      throw new Error(`Output would contain input source: ${program.filename}`);
    }
  }
  validateSchema(schema);

  const models = shouldEmitModels
    ? schema.programs.map((program) => ({
        name: program.name,
        content: emitModels(program, i64),
      }))
    : [];

  const hasServices =
    shouldEmitClients &&
    schema.programs.some((p) => p.ast.service && Object.keys(p.ast.service).length > 0);

  await publishOutput(output, async (staging) => {
    if (hasServices) {
      const clientsDir = path.join(staging, "clients");
      await mkdir(clientsDir);
      for (const program of schema.programs) {
        const clientFiles = emitProgramClients(program);
        if (clientFiles.length > 0) {
          const programClientsDir = path.join(clientsDir, program.name);
          await mkdir(programClientsDir, { recursive: true });
          for (const file of clientFiles) {
            await writeFile(path.join(clientsDir, file.relativePath), file.content);
          }
          await writeFile(path.join(programClientsDir, "index.ts"), emitProgramIndex(program));
        }
      }
      await writeFile(path.join(clientsDir, "services.ts"), emitServicesRegistry(schema));
      await writeFile(path.join(clientsDir, "index.ts"), emitClientsRootIndex(schema));
    }

    if (shouldEmitModels) {
      const types = path.join(staging, "models");
      await mkdir(types);
      for (const model of models) {
        await writeFile(path.join(types, `${model.name}.ts`), model.content);
      }

      const shouldEmitSplitMetadata = options.splitMetadata || shouldEmitClients;
      const indexLines = ["// Generated by tsthrift. Do not edit."];
      if (hasServices) {
        indexLines.push('export * from "./clients/index.js";');
      }
      if (shouldEmitSplitMetadata) {
        indexLines.push('export { loadMetadata } from "./metadata/index.js";');
      }
      for (const root of schema.roots) {
        indexLines.push(`export * as ${root.name} from "./models/${root.name}.js";`);
      }
      await writeFile(path.join(staging, "index.ts"), `${indexLines.join("\n")}\n`);
    }

    const shouldEmitMetadataJson = options.metadataJson ?? !shouldEmitModels;

    if (shouldEmitMetadataJson) {
      await writeFile(
        path.join(staging, "metadata.json"),
        emitMetadata(schema, { minify: options.minify }),
      );
    }

    const shouldEmitSplitMetadata = options.splitMetadata || shouldEmitClients;
    if (shouldEmitSplitMetadata) {
      const metadataDir = path.join(staging, "metadata");
      await mkdir(metadataDir);
      const split = emitSplitMetadata(schema, { minify: options.minify });
      for (const item of split) {
        await writeFile(path.join(metadataDir, item.filename), item.content);
      }
      await writeFile(path.join(metadataDir, "index.ts"), emitMetadataLoader(schema));
    }

    if (options.package) {
      const pkgJson = {
        name: options.packageName ?? path.basename(output),
        version: "0.0.0",
        type: "module",
        main: "./index.js",
        types: "./index.d.ts",
        files: ["**/*.js", "**/*.d.ts", "**/*.json"],
        peerDependencies: {
          "@vality/tsthrift": "*",
        },
      };
      await writeFile(path.join(staging, "package.json"), JSON.stringify(pkgJson, null, 2) + "\n");
      const tsconfig = {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          declaration: true,
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
        },
      };
      await writeFile(
        path.join(staging, "tsconfig.json"),
        JSON.stringify(tsconfig, null, 2) + "\n",
      );
    }

    await writeFile(
      path.join(staging, "generation.json"),
      JSON.stringify(
        {
          i64,
          models: shouldEmitModels,
          clients: shouldEmitClients,
          minify: options.minify ?? false,
          splitMetadata: options.splitMetadata ?? false,
          metadataJson: shouldEmitMetadataJson,
          namespaces: schema.roots.map((root) => root.name),
        },
        null,
        2,
      ) + "\n",
    );
  });

  return {
    i64,
    models: shouldEmitModels,
    clients: shouldEmitClients,
    modules: schema.programs.map((program) => program.name),
    output,
  };
}
