import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSchema } from "./load-schema.ts";
import { validateSchema } from "./validate-schema.ts";
import { emitModels } from "./emit-models.ts";
import {
  emitProgramServices,
  emitProgramIndex,
  emitServicesRegistry,
  emitServicesRootIndex,
} from "./emit-services.ts";
import { emitMetadata } from "../metadata/emit-metadata.ts";
import { publishOutput } from "./publish-output.ts";
import { emitSplitMetadata, emitMetadataLoader } from "../metadata/emit-split-metadata.ts";
import { parseI64Mode } from "./i64-mode.ts";
import type { I64Mode } from "./i64-mode.ts";
import { bundleOutput } from "./bundle.ts";

export interface GenerateOptions {
  input: string;
  output?: string;
  bundle?: boolean;
  dist?: string;
  includes?: string[];
  namespaces?: string[];
  models?: boolean;
  services?: boolean;
  metadataJson?: boolean;
  i64?: I64Mode;
  allowDuplicateModules?: boolean;
}

export interface GenerateResult {
  i64: I64Mode;
  models: boolean;
  services: boolean;
  bundled?: boolean;
  compilerVersion?: string;
  modules: string[];
  output: string;
  dist?: string;
}

export async function generate(options: GenerateOptions): Promise<GenerateResult> {
  const input = path.resolve(options.input);
  const output = path.resolve(options.output ?? "generated");
  const dist = path.resolve(options.dist ?? "dist");
  const includes = [input, ...(options.includes ?? []).map((root) => path.resolve(root))];
  const shouldEmitModels = options.models ?? true;
  const shouldEmitServices = shouldEmitModels && options.services !== false;
  const i64 = parseI64Mode(options.i64);

  const schema = await loadSchema(
    input,
    includes,
    options.namespaces,
    options.allowDuplicateModules,
  );
  for (const program of schema.programs) {
    const relative = path.relative(output, program.filename);
    if (!relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)) {
      throw new Error(`Output would contain input source: ${program.filename}`);
    }
  }
  validateSchema(schema);

  const models = shouldEmitModels
    ? schema.programs.map((program) => ({
        name: program.name,
        content: emitModels(program, i64),
      }))
    : [];

  const hasServices =
    shouldEmitServices &&
    schema.programs.some((p) => p.ast.service && Object.keys(p.ast.service).length > 0);

  await publishOutput(output, async (staging) => {
    if (hasServices) {
      const servicesDir = path.join(staging, "services");
      await mkdir(servicesDir);
      for (const program of schema.programs) {
        const serviceFiles = emitProgramServices(program);
        if (serviceFiles.length > 0) {
          const programServicesDir = path.join(servicesDir, program.name);
          await mkdir(programServicesDir, { recursive: true });
          for (const file of serviceFiles) {
            await writeFile(path.join(servicesDir, file.relativePath), file.content);
          }
          await writeFile(path.join(programServicesDir, "index.ts"), emitProgramIndex(program));
        }
      }
      await writeFile(path.join(servicesDir, "services.ts"), emitServicesRegistry(schema));
      await writeFile(path.join(servicesDir, "index.ts"), emitServicesRootIndex(schema));
    }

    if (shouldEmitModels) {
      const modelsDir = path.join(staging, "models");
      await mkdir(modelsDir);
      for (const model of models) {
        await writeFile(path.join(modelsDir, `${model.name}.ts`), model.content);
      }

      const metadataDir = path.join(staging, "metadata");
      await mkdir(metadataDir);
      const split = emitSplitMetadata(schema);
      for (const item of split) {
        await writeFile(path.join(metadataDir, item.filename), item.content);
      }
      await writeFile(path.join(metadataDir, "index.ts"), emitMetadataLoader(schema));

      const indexLines = ["// Generated by tsthrift. Do not edit."];
      for (const program of schema.programs) {
        indexLines.push(`export * as ${program.name} from "./models/${program.name}.js";`);
      }
      if (hasServices) {
        indexLines.push('export * as services from "./services/index.js";');
        indexLines.push('export * from "./services/services.js";');
      }
      indexLines.push('export { loadMetadata } from "./metadata/index.js";');
      await writeFile(path.join(staging, "index.ts"), `${indexLines.join("\n")}\n`);
    }

    const shouldEmitMetadataJson = options.metadataJson ?? !shouldEmitModels;
    if (shouldEmitMetadataJson) {
      await writeFile(path.join(staging, "metadata.json"), emitMetadata(schema));
    }

    if (shouldEmitModels) {
      const tsconfig = {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          declaration: true,
          isolatedDeclarations: true,
          strict: true,
          skipLibCheck: true,
          resolveJsonModule: true,
        },
      };
      await writeFile(
        path.join(staging, "tsconfig.json"),
        JSON.stringify(tsconfig, null, 2) + "\n",
      );
    }
  });

  const isBundled = Boolean(options.bundle && shouldEmitModels);
  if (isBundled) {
    await publishOutput(dist, async (stagingDist) => {
      await bundleOutput({
        entry: path.join(output, "index.ts"),
        outDir: stagingDist,
        tsconfig: path.join(output, "tsconfig.json"),
        cwd: path.dirname(output),
      });
    });
  }

  return {
    i64,
    models: shouldEmitModels,
    services: shouldEmitServices,
    bundled: isBundled,
    modules: schema.programs.map((program) => program.name),
    output,
    dist: isBundled ? dist : undefined,
  };
}
