import { emitCodecs } from "./native/emit-codecs.ts";
import {
  emitNativeClients,
  emitNativeClientsIndex,
  emitNativeRegistry,
} from "./native/emit-clients.ts";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSchema } from "./load-schema.ts";
import { validateSchema } from "./validate-schema.ts";
import { apacheGenerator, compilerVersion, generateJavaScript } from "./run-thrift.ts";
import { emitModels } from "./emit-models.ts";
import { emitClients, emitClientsIndex, emitServicesRegistry } from "./emit-clients.ts";
import { publishOutput } from "./publish-output.ts";
import { emitMetadata } from "../metadata/emit-metadata.ts";
import { validateApache } from "./validate-apache.ts";
import { parseI64Mode } from "./i64-mode.ts";
import type { I64Mode } from "./i64-mode.ts";

export type GenerateTarget = "metadata" | "models" | "apache" | "native";

export interface GenerateOptions {
  input: string;
  output: string;
  includes?: string[];
  namespaces?: string[];
  compiler?: string;
  target?: GenerateTarget;
  i64?: I64Mode;
}

export interface GenerateResult {
  target: GenerateTarget;
  i64: I64Mode;
  compilerVersion?: string;
  modules: string[];
  output: string;
}

export async function generate(options: GenerateOptions): Promise<GenerateResult> {
  const input = path.resolve(options.input);
  const output = path.resolve(options.output);
  const includes = [input, ...(options.includes ?? []).map((root) => path.resolve(root))];
  const compiler = options.compiler ?? "thrift";
  const target = options.target ?? "models";
  const i64 = parseI64Mode(options.i64);
  if (!["metadata", "models", "apache", "native"].includes(target))
    throw new Error(`Unknown generation target: ${target}`);
  if (options.compiler && target !== "apache")
    throw new Error("--compiler requires --target apache");
  const schema = await loadSchema(input, includes, options.namespaces);
  for (const program of schema.programs) {
    const relative = path.relative(output, program.filename);
    if (!relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative)) {
      throw new Error(`Output would contain input source: ${program.filename}`);
    }
  }
  validateSchema(schema);
  const version = target === "apache" ? await compilerVersion(compiler) : undefined;
  if (target === "apache") validateApache(schema);
  const models =
    target === "metadata"
      ? []
      : schema.programs.map((program) => ({
          name: program.name,
          content: emitModels(program, i64, target === "native" ? "Uint8Array" : "string"),
        }));
  const clients =
    target === "apache"
      ? schema.programs.flatMap(emitClients)
      : target === "native"
        ? schema.programs.flatMap(emitNativeClients)
        : [];
  if (new Set(clients.map((client) => client.name)).size !== clients.length)
    throw new Error("Duplicate service names cannot share a client export");
  const codecs =
    target === "native"
      ? schema.programs.map((program) => ({
          name: program.name,
          content: emitCodecs(program, i64),
        }))
      : [];
  await publishOutput(output, async (staging) => {
    if (target === "apache") {
      const js = path.join(staging, "internal");
      await mkdir(js);
      await generateJavaScript(compiler, schema, includes, js);
      await writeFile(path.join(js, "package.json"), '{"type":"commonjs"}\n');
    }
    if (codecs.length) {
      const directory = path.join(staging, "codecs");
      await mkdir(directory);
      for (const codec of codecs)
        await writeFile(path.join(directory, `${codec.name}.ts`), codec.content);
    }
    if (clients.length > 0) {
      const clientsDir = path.join(staging, "clients");
      await mkdir(clientsDir);
      for (const client of clients) {
        const filename = path.join(clientsDir, `${client.name}.ts`);
        await mkdir(path.dirname(filename), { recursive: true });
        await writeFile(filename, client.content);
      }
      const serviceEntries = schema.programs.flatMap((program) =>
        Object.keys(program.ast.service ?? {}).map((serviceName) => ({
          serviceName,
          programName: program.name,
        })),
      );
      await writeFile(
        path.join(clientsDir, "services.ts"),
        target === "native"
          ? emitNativeRegistry(schema.programs)
          : emitServicesRegistry(serviceEntries),
      );
      await writeFile(
        path.join(clientsDir, "index.ts"),
        target === "native" ? emitNativeClientsIndex(schema.programs) : emitClientsIndex(clients),
      );
    }
    if (target !== "metadata") {
      const types = path.join(staging, "models");
      await mkdir(types);
      for (const model of models)
        await writeFile(path.join(types, `${model.name}.ts`), model.content);

      const indexLines = ["// Generated by tsthrift. Do not edit."];
      if (clients.length > 0) {
        indexLines.push(
          target === "native"
            ? 'export * as clients from "./clients/index.js";'
            : 'export * from "./clients/index.js";',
        );
      }
      for (const root of schema.roots) {
        indexLines.push(`export * as ${root.name} from "./models/${root.name}.js";`);
      }
      await writeFile(path.join(staging, "index.ts"), `${indexLines.join("\n")}\n`);
    }
    await writeFile(path.join(staging, "metadata.json"), emitMetadata(schema));
    await writeFile(
      path.join(staging, "generation.json"),
      JSON.stringify(
        {
          compilerVersion: version,
          target,
          i64,
          ...(target === "apache" ? { generator: apacheGenerator } : {}),
          namespaces: schema.roots.map((root) => root.name),
        },
        null,
        2,
      ) + "\n",
    );
  });
  return {
    target,
    i64,
    compilerVersion: version,
    modules: schema.programs.map((program) => program.name),
    output,
  };
}
