import type { Program, Schema } from "../compiler/load-schema.ts";
import { getTransitiveDependencies } from "./dependencies.ts";
import type { EmitMetadataOptions } from "./emit-metadata.ts";

export interface EmittedModuleMetadata {
  name: string;
  filename: string;
  content: string;
}

/** Emits an individual TypeScript module containing the parsed Thrift AST metadata. */
export function emitModuleMetadata(
  program: Program,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata {
  const meta = {
    name: program.name,
    path: program.path,
    ast: program.ast,
  };
  const body = options?.minify ? JSON.stringify(meta) : JSON.stringify(meta, null, 2);

  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    `export const metadata: Metadata = ${body};`,
    "",
    "export default metadata;",
    "",
  ];

  return {
    name: program.name,
    filename: `${program.name}.ts`,
    content: lines.join("\n"),
  };
}

export function emitSplitMetadata(
  schema: Schema,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata[] {
  return schema.programs.map((program) => emitModuleMetadata(program, options));
}

/**
 * Emits the metadata index module containing static loaders for each namespace
 * with its precalculated transitive dependency tree.
 */
export function emitMetadataLoader(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import { createMetadataLoader, type Metadata } from "@vality/tsthrift";',
    "",
    "/**",
    " * Loads the full metadata closure for the specified namespace including all transitive dependencies.",
    " */",
    "export const loadMetadata: (namespace: string) => Promise<Metadata[]> = createMetadataLoader({",
  ];

  for (const program of schema.programs) {
    const deps = getTransitiveDependencies(program);
    lines.push(`  ${JSON.stringify(program.name)}: () =>`);
    lines.push("    Promise.all([");
    for (const dep of deps) {
      lines.push(`      import("./${dep.name}.js"),`);
    }
    lines.push("    ]),");
  }

  lines.push("});");
  lines.push("");

  return lines.join("\n");
}
