import type { Program, Schema } from "../compiler/load-schema.ts";
import { getTransitiveDependencies } from "./dependencies.ts";
import type { EmitMetadataOptions } from "./emit-metadata.ts";

export interface EmittedModuleMetadata {
  name: string;
  filename: string;
  content: string;
}

/** Emits an individual TypeScript module containing the parsed Thrift AST metadata. */
export function emitModuleMetadata(
  program: Program,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata {
  const meta = {
    name: program.name,
    path: program.path,
    ast: program.ast,
  };
  const body = options?.minify ? JSON.stringify(meta) : JSON.stringify(meta, null, 2);

  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    `export const thriftMetadata: Metadata = ${body};`,
    "",
    "export default thriftMetadata;",
    "",
  ];

  return {
    name: program.name,
    filename: "metadata.ts",
    content: lines.join("\n"),
  };
}

export function emitSplitMetadata(
  schema: Schema,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata[] {
  return schema.localPrograms.map((program) => emitModuleMetadata(program, options));
}

/**
 * Emits the local metadata loader for a namespace with its precalculated transitive dependency tree.
 */
export function emitNamespaceMetadataLoader(program: Program): string {
  const deps = getTransitiveDependencies(program);
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    "let metadataPromise: Promise<Metadata[]> | undefined;",
    "",
    "/**",
    ` * Loads the full metadata closure for the ${JSON.stringify(program.name)} namespace and its dependencies.`,
    " */",
    "export function loadThriftMetadata(): Promise<Metadata[]> {",
    "  if (!metadataPromise) {",
    "    metadataPromise = Promise.all([",
  ];

  for (const dep of deps) {
    if (dep.name === program.name) {
      lines.push('      import("./metadata.js"),');
    } else if (dep.external) {
      const metaPath = dep.external.metadataPath ?? dep.external.importPath;
      lines.push(`      import(${JSON.stringify(metaPath)}),`);
    } else {
      lines.push(`      import("../${dep.name}/metadata.js"),`);
    }
  }

  lines.push("    ]).then(async (modules) => {");
  lines.push("      const results = await Promise.all(");
  lines.push("        modules.map(async (raw, index) => {");
  lines.push(`          const namespace = ${JSON.stringify(deps.map((dep) => dep.name))}[index]!;`);
  lines.push("          const m = raw as Record<string, unknown>;");
  lines.push('          if (typeof m.loadThriftMetadata === "function") {');
  lines.push(
    "            return await (m.loadThriftMetadata as (namespace: string) => Promise<Metadata[]>)(namespace);",
  );
  lines.push("          }");
  lines.push("          const meta = (m.thriftMetadata ?? m.metadata ?? m.default ?? m) as");
  lines.push("            | Metadata");
  lines.push("            | Metadata[];");
  lines.push("          return Array.isArray(meta) ? meta : [meta];");
  lines.push("        }),");
  lines.push("      );");
  lines.push("      const seen = new Set<string>();");
  lines.push("      const deduped: Metadata[] = [];");
  lines.push("      for (const item of results.flat()) {");
  lines.push("        const key = item.name || item.path;");
  lines.push("        if (!seen.has(key)) {");
  lines.push("          seen.add(key);");
  lines.push("          deduped.push(item);");
  lines.push("        }");
  lines.push("      }");
  lines.push("      return deduped;");
  lines.push("    });");
  lines.push("  }");
  lines.push("  return metadataPromise;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Emits the root metadata index module delegating to each namespace's local loader.
 */
export function emitMetadataLoader(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
  ];

  if (schema.externalPrograms.length > 0) {
    lines.push("export interface ExternalNamespaceDescriptor {");
    lines.push("  readonly name: string;");
    lines.push("  readonly package: string;");
    lines.push("  readonly importPath: string;");
    lines.push("  readonly isExternal: true;");
    lines.push("}");
    lines.push("");
    lines.push("export const EXTERNAL_NAMESPACES: Record<string, ExternalNamespaceDescriptor> = {");
    for (const p of schema.externalPrograms) {
      const ext = p.external!;
      lines.push(`  ${JSON.stringify(p.name)}: {`);
      lines.push(`    name: ${JSON.stringify(p.name)},`);
      lines.push(`    package: ${JSON.stringify(ext.package ?? "")},`);
      lines.push(`    importPath: ${JSON.stringify(ext.importPath)},`);
      lines.push("    isExternal: true,");
      lines.push("  },");
    }
    lines.push("};");
    lines.push("");
  }

  lines.push("const cache = new Map<string, Promise<Metadata[]>>();");
  lines.push("const loaders: Record<string, () => Promise<Metadata[]>> = {");

  for (const program of schema.localPrograms) {
    lines.push(
      `  ${JSON.stringify(program.name)}: () => import("./${program.name}/load-metadata.js").then((m) => m.loadThriftMetadata()),`,
    );
  }

  for (const program of schema.externalPrograms) {
    const ext = program.external!;
    const metaPath = ext.metadataPath ?? ext.importPath;
    lines.push(
      `  ${JSON.stringify(program.name)}: async () => {`,
      `    const raw = await import(${JSON.stringify(metaPath)});`,
      "    const m = raw as Record<string, unknown>;",
      '    if (typeof m.loadThriftMetadata === "function") {',
      `      return await (m.loadThriftMetadata as (namespace: string) => Promise<Metadata[]>)(${JSON.stringify(program.name)});`,
      "    }",
      "    const meta = (m.thriftMetadata ?? m.metadata ?? m.default ?? m) as",
      "      | Metadata",
      "      | Metadata[];",
      "    return (Array.isArray(meta) ? meta : [meta]) as Metadata[];",
      "  },",
    );
  }

  lines.push("};");
  lines.push("");
  lines.push("/**");
  lines.push(
    " * Loads the full metadata closure for the specified namespace including all transitive dependencies.",
  );
  lines.push(" */");
  lines.push("export function loadThriftMetadata(namespace: string): Promise<Metadata[]> {");
  lines.push("  let cached = cache.get(namespace);");
  lines.push("  if (!cached) {");
  lines.push("    const loader = loaders[namespace];");
  lines.push("    if (!loader) {");
  lines.push("      return Promise.reject(new Error(`Unknown metadata namespace: ${namespace}`));");
  lines.push("    }");
  lines.push("    cached = loader();");
  lines.push("    cache.set(namespace, cached);");
  lines.push("  }");
  lines.push("  return cached;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
