import type { Program, Schema } from "../compiler/load-schema.ts";
import { getTransitiveDependencies } from "./dependencies.ts";
import type { EmitMetadataOptions } from "./emit-metadata.ts";

export interface EmittedModuleMetadata {
  name: string;
  filename: string;
  content: string;
}

/** Emits an individual TypeScript module containing the parsed Thrift AST metadata. */
export function emitModuleMetadata(
  program: Program,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata {
  const meta = {
    name: program.name,
    path: program.path,
    ast: program.ast,
  };
  const body = options?.minify ? JSON.stringify(meta) : JSON.stringify(meta, null, 2);

  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    `export const thriftMetadata: Metadata = ${body};`,
    "",
    "export default thriftMetadata;",
    "",
  ];

  return {
    name: program.name,
    filename: "metadata.ts",
    content: lines.join("\n"),
  };
}

export function emitSplitMetadata(
  schema: Schema,
  options?: EmitMetadataOptions,
): EmittedModuleMetadata[] {
  return schema.programs.map((program) => emitModuleMetadata(program, options));
}

/**
 * Emits the local metadata loader for a namespace with its precalculated transitive dependency tree.
 */
export function emitNamespaceMetadataLoader(program: Program): string {
  const deps = getTransitiveDependencies(program);
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    "let metadataPromise: Promise<Metadata[]> | undefined;",
    "",
    "/**",
    ` * Loads the full metadata closure for the ${JSON.stringify(program.name)} namespace and its dependencies.`,
    " */",
    "export function loadThriftMetadata(): Promise<Metadata[]> {",
    "  if (!metadataPromise) {",
    "    metadataPromise = Promise.all([",
  ];

  for (const dep of deps) {
    if (dep.name === program.name) {
      lines.push('      import("./metadata.js"),');
    } else {
      lines.push(`      import("../${dep.name}/metadata.js"),`);
    }
  }

  lines.push("    ]).then((modules) =>");
  lines.push("      modules.map((m) => (m.thriftMetadata ?? m.default ?? m) as Metadata),");
  lines.push("    );");
  lines.push("  }");
  lines.push("  return metadataPromise;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * Emits the root metadata index module delegating to each namespace's local loader.
 */
export function emitMetadataLoader(schema: Schema): string {
  const lines = [
    "// Generated by tsthrift. Do not edit.",
    'import type { Metadata } from "@vality/tsthrift";',
    "",
    "const cache = new Map<string, Promise<Metadata[]>>();",
    "const loaders: Record<string, () => Promise<Metadata[]>> = {",
  ];

  for (const program of schema.programs) {
    lines.push(
      `  ${JSON.stringify(program.name)}: () => import("./${program.name}/load-metadata.js").then((m) => m.loadThriftMetadata()),`,
    );
  }

  lines.push("};");
  lines.push("");
  lines.push("/**");
  lines.push(
    " * Loads the full metadata closure for the specified namespace including all transitive dependencies.",
  );
  lines.push(" */");
  lines.push("export function loadThriftMetadata(namespace: string): Promise<Metadata[]> {");
  lines.push("  let cached = cache.get(namespace);");
  lines.push("  if (!cached) {");
  lines.push("    const loader = loaders[namespace];");
  lines.push("    if (!loader) {");
  lines.push("      return Promise.reject(new Error(`Unknown metadata namespace: ${namespace}`));");
  lines.push("    }");
  lines.push("    cached = loader();");
  lines.push("    cache.set(namespace, cached);");
  lines.push("  }");
  lines.push("  return cached;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
