import "@angular/compiler";
import { HttpClient, HttpXhrBackend } from "@angular/common/http";
import {
  type EnvironmentInjector,
  createEnvironmentInjector,
  runInInjectionContext,
} from "@angular/core";
import { firstValueFrom } from "rxjs";
import { ThriftHttpError, ThriftTimeoutError, createMetadataClient } from "@vality/tsthrift";
import {
  createHttpClientFetch,
  getServiceToken,
  provideThriftConfig,
  provideThriftServices,
} from "../src/index.ts";
// Generated by the browser smoke runner before Vite resolves this entry.
// @ts-expect-error The virtual module exists only during the smoke build.
import { THRIFT_SERVICES_LIST, example } from "__generated__";

function check(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

export async function runBrowserSmoke() {
  const endpoint = new URL("/thrift", location.href).href;
  const httpInjector = createEnvironmentInjector([], null as unknown as EnvironmentInjector);
  const http = runInInjectionContext(
    httpInjector,
    () => new HttpClient(new HttpXhrBackend({ build: () => new XMLHttpRequest() })),
  );
  const angularFetch = createHttpClientFetch(http);
  const bytes = new Uint8Array([0, 128, 255]);
  for (const fetch of [globalThis.fetch, angularFetch]) {
    for (const i64Mode of ["number", "bigint"] as const) {
      const client = await createMetadataClient({
        metadata: () => example.Example.getMetadata(),
        namespace: "example",
        serviceName: "Example",
        endpoint,
        fetch,
        i64Mode,
        headers: { Authorization: "old" },
      });
      const result = await client.echo(bytes, i64Mode === "number" ? 42 : 42n, {
        headers: { authorization: "new" },
      });
      check(
        result instanceof Uint8Array && String(result) === String(bytes),
        "Binary roundtrip failed",
      );
    }
  }
  const injector = createEnvironmentInjector(
    [
      provideThriftConfig({ endpoint, fetch: angularFetch, headers: { authorization: "new" } }),
      provideThriftServices(THRIFT_SERVICES_LIST),
    ],
    null as unknown as EnvironmentInjector,
  );
  try {
    const client = injector.get(getServiceToken(example.Example)) as any;
    check(
      String(await firstValueFrom(client.echo(bytes, 42))) === String(bytes),
      "Generated Angular DI call failed",
    );
  } finally {
    injector.destroy();
  }

  for (const [route, expected] of [
    ["/503", ThriftHttpError],
    ["/slow", ThriftTimeoutError],
  ] as const) {
    const client = example.createExample({
      endpoint: new URL(route, location.href).href,
      fetch: angularFetch,
      timeoutMs: 150,
    });
    try {
      await client.echo(bytes, 42);
      throw new Error("Expected transport failure");
    } catch (error) {
      check(error instanceof expected, `Unexpected error for ${route}: ${String(error)}`);
    }
  }
  const controller = new AbortController();
  const client = example.createExample({
    endpoint: new URL("/slow", location.href).href,
    fetch: angularFetch,
  });
  const pending = client.echo(bytes, 42, { signal: controller.signal });
  setTimeout(() => controller.abort(new Error("browser cancel")), 50);
  try {
    await pending;
    throw new Error("Expected cancellation");
  } catch (error) {
    check(error instanceof Error && error.message === "browser cancel", "Cancellation reason lost");
  }
  httpInjector.destroy();
  return "Chromium passed: fetch/XHR, binary/i64, generated factory, Angular DI/Observable, HTTP errors, timeout, cancellation.";
}
